// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr3b4sLhPbe44gPynCZKIysYvSo2iSAgE',
    appId: '1:6855081944:android:99f67e991cde1edf77fcad',
    messagingSenderId: '6855081944',
    projectId: 'epitrack-c79db',
    storageBucket: 'epitrack-c79db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcwEipG0lFLQiALs1x1bapovbMIsADztE',
    appId: '1:6855081944:ios:265216c92c12c0e877fcad',
    messagingSenderId: '6855081944',
    projectId: 'epitrack-c79db',
    storageBucket: 'epitrack-c79db.firebasestorage.app',
    iosBundleId: 'com.example.epitrack',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx-N8DcYGhjJlawmZLsSNwnjNg47VBK7o',
    appId: '1:6855081944:web:d13cd704f1906cfa77fcad',
    messagingSenderId: '6855081944',
    projectId: 'epitrack-c79db',
    authDomain: 'epitrack-c79db.firebaseapp.com',
    storageBucket: 'epitrack-c79db.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcwEipG0lFLQiALs1x1bapovbMIsADztE',
    appId: '1:6855081944:ios:265216c92c12c0e877fcad',
    messagingSenderId: '6855081944',
    projectId: 'epitrack-c79db',
    storageBucket: 'epitrack-c79db.firebasestorage.app',
    iosBundleId: 'com.example.epitrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx-N8DcYGhjJlawmZLsSNwnjNg47VBK7o',
    appId: '1:6855081944:web:1cfcf4d2028fc24077fcad',
    messagingSenderId: '6855081944',
    projectId: 'epitrack-c79db',
    authDomain: 'epitrack-c79db.firebaseapp.com',
    storageBucket: 'epitrack-c79db.firebasestorage.app',
  );

}